# Generated by Django 5.1.1 on 2024-09-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_report', '0002_alter_storestatus_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storestatus',
            index=models.Index(fields=['store_id', 'timestamp_utc'], name='store_repor_store_i_5d17a6_idx'),
        ),
    ]
