# Generated by Django 5.1.1 on 2024-09-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_report', '0003_storestatus_store_repor_store_i_5d17a6_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['store_id', 'day_of_week', 'start_time_local'], name='store_repor_store_i_b1f686_idx'),
        ),
    ]
